apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pubsub
  namespace: default
spec:
  type: pubsub.kafka
  version: v1
  metadata:
  - name: brokers
    value: "localhost:29092"
  - name: consumerGroup
    value: "Consumer_Group_First"
  - name: clientID
    value: ""Sample_Client_ID"
  - name: authType 
    value: "none"
  - name: maxMessageBytes
    value: 1024
  - name: consumeRetryInterval
    value: 200ms
  - name: version
    value: 0.10.2.0
  - name: disableTls 
    value: "true"