apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: awssecretmanager
  namespace: default
spec:
  type: secretstores.aws.secretmanager
  version: v1
  metadata:
    - name: region
      value: 'us-east-1'
    - name: accessKey
      value: ''
    - name: secretKey
      value: ''
