version: '3.3'

services:
  mssql:
    container_name: mssql
    image: mcr.microsoft.com/mssql/server
    ports:
      - '1433:1433'
    environment:
      SA_PASSWORD: 'Welcome@1'
      ACCEPT_EULA: 'Y'

  mongodb:
    container_name: mongodb
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=base
    ports:
      - '27017:27017'
    volumes:
      - ./data:/data/db

  tracing:
    container_name: tracing
    image: 'openzipkin/zipkin'
    ports:
      - 9411:9411

  dapr:
    container_name: dapr
    image: 'daprio/dapr'
    command: ['./placement', '-port', '50006']
    ports:
      - 50006:50006

  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181

  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
